### ISSUE TITLE
输入城市ID后手动更新显示 'ID不能为空' 的问题

### ISSUE THREAD

**Issue by MayoPickle** [Huiyicc/hw_weather_plugin#1]
![image](https://github.com/Huiyicc/hw_weather_plugin/assets/29362008/8d2bebe8-2988-4e53-9b1d-dbaa4a157ae6)

助手 Version: Pre0.0.3 (93ada36)
Firmware version: 12/04

**Comment by Huiyicc** [comment]
已收到，换键盘了，过两天等板子到了会进行修复

**Comment by Huiyicc** [comment]
下载最新release即可解决
